Task3
TblPK/fintech pull request #5
Opened 2023-10-01 20:11 UTC by TblPK

2023-10-02 07:16 UTC, madoed commented on build.gradle
> +//}
Лучше не коммитить закомментированное, т.к. не факт, что оно понадобиться

2023-10-02 07:24 UTC, madoed commented on src/main/java/com/weather/controllers/WeatherController.java
> +    public ResponseEntity<List<Weather>> getCurrentWeather(@PathVariable("city") @Parameter(description = "City Name") String cityName,
А почему стал использовать ResponseEntity?

У тебя нотификация `@RestController` которая поддерживает автоматическое оборачивание в ResponseEntity

2023-10-02 07:26 UTC, madoed commented on src/main/java/com/weather/controllers/WeatherController.java
> +        if (weathers.isEmpty()) return ResponseEntity.notFound().build();
Выглядит так, что можно заменить связкой Exception на уровне сервиса и ControllerAdvice + ExceptionHandler

Подробнее [тут ](https://www.baeldung.com/exception-handling-for-rest-with-spring#controlleradvice)

2023-10-02 07:28 UTC, madoed commented on src/main/java/com/weather/controllers/WeatherController.java
> +    @GetMapping("/get-all")
Лучше сделать просто / , обычно если не передаём id - это имеется ввиду - верни мне всё что есть

2023-10-02 07:32 UTC, madoed commented on src/main/java/com/weather/dao/WeatherDao.java
> +    public final List<Weather> tempDB = new ArrayList<>();
Почему не Map с ключом по id города?

2023-10-02 07:34 UTC, madoed commented on src/main/java/com/weather/models/WeatherService.java
> +                .filter(w -> w.getCityName().equals(cityName) &&
На каждый чих мы будем пробегаться по всей коллекции - выглядит как лишняя работа

2023-10-02 07:35 UTC, madoed commented on src/main/java/com/weather/models/WeatherService.java
> +        if (optional.isEmpty()) weathers.add(weather);
Лучше писать с { } даже для 1-ого действия иначе можно легко ошибиться

2023-10-02 07:35 UTC, madoed requested changes
Необходимо доработать по комментариям

2023-10-02 07:35 UTC, madoed commented
Так же не увидел сгенерированного openapi.yml

2023-10-05 06:31 UTC, madoed commented
Не забудь на edu платформе проставить - что замечания пофикшены иначе мне нотификация не приходит

2023-10-05 07:37 UTC, TblPK commented
> Не забудь на edu платформе проставить - что замечания пофикшены иначе мне нотификация не приходит

2023-10-05 07:42 UTC, TblPK commented
> Не забудь на edu платформе проставить - что замечания пофикшены иначе мне нотификация не приходит

Хорошо, я просто ещё не все сделал. Из-за вуза не успеваю.

2023-10-06 07:20 UTC, madoed commented on src/main/java/com/weather/controllers/WeatherController.java
> +    public void createWeather(
Я бы ещё вернул тут созданный объект. Полезно, когда генерится id либо любые другие поля (например дата создания и модификации)

2023-10-06 07:21 UTC, madoed commented on src/main/java/com/weather/controllers/WeatherController.java
> +    public void updateWeather(
Я бы ещё вернул тут модифицированный объект. Полезно, когда генерится id либо любые другие поля (например дата создания и модификации)

2023-10-06 07:21 UTC, madoed approved these changes
Оставил мини комментарии на будущее, на зачёт не влияют

2023-10-06 18:47 UTC, merged