Практика по работе с СУБД
TblPK/fintech pull request #7
Opened 2023-10-22 21:18 UTC by TblPK

2023-10-23 07:26 UTC, madoed commented
`При старте приложения должны заполнятся справочные таблицы с городами с помощью скриптов liquibase`

Таблицы не заполняются данными, нужно доделать

```
4) Написать CRUD методы для получения, добавления изменения и удаления данных из БД используя 2 реализации:

JDBC
Hibernate
```

Нужно замапить существующие контроллеры/сервисы на эти две реализации. Плюс Hibernate реализации пусты, там явно надо будет дописать нужные запросы. В JDBC скорее всего тоже.

2023-10-23 07:26 UTC, madoed requested changes
Нужно доделать

2023-10-23 07:26 UTC, madoed commented on src/main/java/com/weather/repositories/springdatajpa/CityJpaRepository.java
> +
Лишняя пустая строка

2023-10-23 07:26 UTC, madoed commented on src/main/java/com/weather/repositories/springdatajpa/WeatherJpaRepository.java
> +
Лишняя пустая строка

2023-10-23 07:26 UTC, madoed commented on src/main/java/com/weather/repositories/springjdbc/CityJdbcRepository.java
> +    private static final RowMapper<City> ROW_MAPPER = new BeanPropertyRowMapper<>(City.class);
Лучше написать руками, а не использовать BeanPropertyRowMapper. На это есть несколько причин

- BeanPropertyRowMapper использует рефлексию (хоть и хитро), но это не бесплатно и обычно дорого, по сравнению с ручным RowMapper-ом
- Не всегда получается замапить им правильно поля, особенно в случаях когда имя в БД исторически сложилось неверное, а внутри Entity хочется уже иметь верное.

В рамках ДЗ это норм его использовать, но вот есть такие нюансы

2023-10-23 07:26 UTC, madoed commented on src/main/java/com/weather/repositories/springjdbc/CityJdbcRepository.java
> +        KeyHolder keyHolder = new GeneratedKeyHolder();
А зачем KeyHolder, если он потом не используется?

2023-10-23 07:26 UTC, madoed commented on src/main/java/com/weather/repositories/springjdbc/WeatherJdbcRepository.java
> +        KeyHolder keyHolder = new GeneratedKeyHolder();
А зачем KeyHolder, если он потом не используется?

2023-10-23 07:26 UTC, madoed commented on src/main/java/com/weather/repositories/springjdbc/WeatherJdbcRepository.java
> +        Map<String, Object> params = new LinkedHashMap<>();
А почему LinkedHashMap выбрал?

2023-10-23 07:26 UTC, madoed commented on src/main/resources/application.yaml
> +    generate-ddl: true
Зачем в true? 

Если ниже включен liquibase

2023-10-23 07:26 UTC, madoed commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +            relativeToChangelogFile: true
А почему через sql, а не через структуру в Liquibase?

https://docs.liquibase.com/change-types/create-table.html

2023-10-23 10:56 UTC, TblPK commented on src/main/resources/application.yaml
> +    generate-ddl: true
Проверял работу Jpa, забыл отключить

2023-10-23 10:58 UTC, TblPK commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +            relativeToChangelogFile: true
Понравилось через sql. Стоит переписать?

2023-10-23 12:03 UTC, madoed commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +            relativeToChangelogFile: true
Liquibase нагляднее, в том плане, что, чтобы посмотреть чейндж сет, нужно сходить в 2 места - в сам чейндж сет и в сам sql. А так всё будет в одном месте.

Плюс ещё от описания через их структуру, в том, что оно может генерить sql под разные диалекты (т.е. БД) и получается, если нужно будет сменить БД, то у нас уменьшиться кол-во работы, при условии, что некоторые DDL скрипты будут разнится для разных диалектов

2023-10-23 12:05 UTC, madoed commented
> `При старте приложения должны заполнятся справочные таблицы с городами с помощью скриптов liquibase`
> 
> Таблицы не заполняются данными, нужно доделать
> 
> ```
> 4) Написать CRUD методы для получения, добавления изменения и удаления данных из БД используя 2 реализации:
> 
> JDBC
> Hibernate
> ```
> 
> Нужно замапить существующие контроллеры/сервисы на эти две реализации. Плюс Hibernate реализации пусты, там явно надо будет дописать нужные запросы. В JDBC скорее всего тоже.

Так, немного погорячился, маппинг это 7 ДЗ, почему то подумал, что оно все вместе сразу идёт. Поэтому в плане реализаций всё норм

2023-10-24 05:59 UTC, madoed approved these changes

2023-10-24 06:16 UTC, madoed approved these changes

2023-10-24 15:04 UTC, merged