7.2 Лекция 6. Бд Часть 2 Практика
TblPK/fintech pull request #8
Opened 2023-10-26 18:17 UTC by TblPK

2023-10-27 13:07 UTC, madoed requested changes

2023-10-27 13:07 UTC, madoed commented on src/main/java/com/weather/services/TransactionalJdbcService.java
> +        });
Это немного не то, что нужно. Это ручное управление транзакцией через механизм Spring-a.

В задачи нужно поработать напрямую с jdbc. как пример статейка - https://www.tutorialspoint.com/jdbc/jdbc-transactions.htm

2023-10-27 13:07 UTC, madoed commented on src/main/java/com/weather/repositories/springjdbc/WeatherJdbcRepository.java
> -    public void insert(Weather weather) {
А почему insert удалил?

2023-10-27 13:07 UTC, madoed commented on src/main/java/com/weather/repositories/springjdbc/WeatherTypeJdbcRepository.java
> -    }
Зачем удалил?

2023-10-27 13:07 UTC, madoed commented on src/main/java/com/weather/services/TransactionalJpaService.java
> +@Transactional(isolation = Isolation.READ_COMMITTED)
А какие ещё можно заюзать? и в каких случаях?

2023-10-27 19:42 UTC, TblPK commented on src/main/java/com/weather/services/TransactionalJpaService.java
> +@Transactional(isolation = Isolation.READ_COMMITTED)
*READ_UNCOMMITTED* (самый быстрый): используется, когда требуется мах актуальность данных, допуская при этом чтение грязное чтение.
*READ_COMMITTED*: обеспечивает чтение только подтвержденных данных, при этом допускается неповторяющееся чтение).
*REPEATABLE_READ*: гарантирует, что при многократном чтении одних и тех же данных результат остается неизменным, допуская при этом фантомное чтение.
*SERIALIZABLE* (самый медленный): обеспечивает максимальную изоляцию транзакций, предотвращая грязное чтение, неповторяющееся чтение и фантомные чтения за счет блокировки данных.

2023-10-27 19:42 UTC, TblPK commented on src/main/java/com/weather/repositories/springjdbc/WeatherTypeJdbcRepository.java
> -    }
Подумал, что не нужно

2023-10-27 19:42 UTC, TblPK commented on src/main/java/com/weather/repositories/springjdbc/WeatherJdbcRepository.java
> -    public void insert(Weather weather) {
Подумал, что не нужно

2023-10-28 13:50 UTC, madoed approved these changes
Ставлю апрув, но задачу засчитаю после ответа по TRANSACTIONAL_NONE - почему решил именно это заюзать

2023-10-28 13:50 UTC, madoed commented on src/main/java/com/weather/repositories/springjdbc/WeatherJdbcRepository.java
> -    public void insert(Weather weather) {
я бы оставил, может пригодиться в след. лекциях

Но на твоё усмотрение

2023-10-28 13:50 UTC, madoed commented on src/main/java/com/weather/services/TransactionalJdbcService.java
> +            connection.setTransactionIsolation(Connection.TRANSACTION_NONE);
А почему TRANSACTION_NONE? В чём смысл использования?

2023-10-28 14:28 UTC, TblPK commented on src/main/java/com/weather/services/TransactionalJdbcService.java
> +            connection.setTransactionIsolation(Connection.TRANSACTION_NONE);
Хороший вопрос. Просто в условии задачи говорилось о реализации с разными уровнями изоляции, но по какой-то причине я решил вовсе убрать изоляцию. Отсутствие изоляции тоже является своего рода изоляцией🤔

2023-10-30 14:15 UTC, merged